### ISSUE TITLE
Convergence for "hello" program

### ISSUE THREAD

**Issue by gil1j** [primaryobjects/AI-Programmer#11]
Hello,

I tried to reproduce your work in the Julia programming language for my master thesis.
I managed to get impressive results and very good convergence for all the most simple tasks that you covered (string, addition, countdown, logic, ...).
The only one that is resisting me at the moment is the program that simply prints "hello". This looks quite stupid considering that "Hi!" and "reddit" work great.

Here is my idea of why it fails : 
In the beginning of the GA, I quickly see patterns appearing in the code that look like this : "100+[++++..]"
Indeed, because of the strange nature of the word hello, this program gives a fitness that is only 4 points away from the perfect score. The problem is that this structure is appearing so fast, and has such a good fitness, that it conquers the whole population very quickly, and the algorithm gets stuck in an evolutionary dead-end.

I don't know if you are still invested in this project, but if you have any insight that could help me I would very much appreciate it !

Thanks,

Jonas Gillain
Royal Military Academy of Belgium

**Comment by primaryobjects** [comment]
Thank you for the comments and trying this with an implementation of Julia. I think it's great to see the project in a new language. Regarding the question, although I'm unsure of specifics regarding the Julia language or compiler, you may want to check the random number generation that it uses.

Please feel free to maintain a fork so that others can share as well. Thank you.
