### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by sychris** [primaryobjects/AI-Programmer#2]
wasn't really sure where to leave you a msg so I figured here was as well as anywhere else.
2 noob thoughts. 
1. Im wondering if the GPU was used (if possible) would this run much faster due to a great number of small operations being used repeatedly.
2. If there was a second fitness rating that was only run after a new best primary fitness was found that had a max value of say 750 where 250 is awarded for a successful compile 250 awarded for no infinite loops and the remaining was rewarded for every char under 250 utilized. after reaching 500 or the first rating drops, the best match that did not harm the first rating is allowed to resume finding matches. at the end you can have an option for finding more optimized second ratings. 

Not sure if that second option would harm the randomality as the extra compiler info might lend to it however it could still be used after a successful completion for finding optimized code.

sorry for the bad English its not my strong suit.

**Comment by primaryobjects** [comment]
Thanks for the ideas. The code currently runs on the CPU, although it takes advantage of multiple cores via [Parallel.ForEach()](https://msdn.microsoft.com/en-us/library/system.threading.tasks.parallel.foreach(v=vs.110).aspx). Yes, it would run much faster on a GPU. I'd like to think speed is just a temporary set-back, as computer will grow faster, in general, over time. 

As far as the second idea for multiple fitnesses, yes this is something that you could try. However, it would probably slow down the generation and could make the code more complicated. :) I've found that the simplest fitness methods typically give better results.

The current code takes into account being able to compile and not run into an infinite loop. There is actually a component of the fitness score that includes number of operations. So that kills off programs that run infinite or too long, and favors shorter executing ones.

Thanks.

**Comment by sychris** [comment]
hmm..  (the enlightened head nod)  thank you for the reply had not dug in to the fitness score code yet, had just ran a hello test and it had returned with a [] loop in the middle of it.  never done any GPU codding myself but this might be the perfect time to learn and test it out...  will repost if I can get it running well.
